# Generated by Django 5.1.1 on 2024-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtitle",
            name="language",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
