# Generated by Django 5.1.1 on 2024-09-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_subtitle_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
