# Generated by Django 5.1.1 on 2024-09-10 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_video_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="name",
        ),
    ]
