version: '3.8'

services:

  web:
    build:
      context: ./video_processing/
      dockerfile: Dockerfile
    command: gunicorn video_processing.wsgi:application --bind 0.0.0.0:8000 # for production
    # command: python manage.py runserver 0.0.0.0:8000 #for local

    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - redis
      - celery
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./video_processing/
    command: ["celery", "-A", "video_processing", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
